### ISSUE TITLE
Ignore non-significant spaces

### ISSUE THREAD

**Issue by rjungheinrich** [Rookfighter/inifile-cpp#12]
Many INI files are edited directly by end users, and some of them want to use spaces to make the contents easy to read.

For example:
```
[SECT1]
  #This comment is indented, as is the following lines, which are also aligned
  John   = 1
  Evelyn = 2
  Lucas  = 3
```
I've made the pull request https://github.com/Rookfighter/inifile-cpp/pull/11 to implement that.

**Comment by Rookfighter** [comment]
Thanks and good work for adding meaningful tests. All merged!

**Comment by rjungheinrich** [comment]
> Thanks and good work for adding meaningful tests. All merged!

You're welcome!  Thanks for putting the library under MIT License so anyone can use it.
