### ISSUE TITLE
ini parsing failed, section not closed

### ISSUE THREAD

**Issue by cathaysia** [Rookfighter/inifile-cpp#21]
I have a ini file:

```ini
[/home/xxx/.gnupg/]
Acls=user::rwx;group::---;other::---

[/home/xxx/.gnupg/.#lkxxx.29271]
Acls=user::rw-;group::r--;other::r--

[/home/xxx/.gnupg/openpgp-revocs.d/xxx.rev]
Acls=user::rw-;group::---;other::---

[/home/xxx/.gnupg/private-keys-v1.d/xxx.key]
Acls=user::rw-;group::---;other::---

[/home/xxx/.gnupg/private-keys-v1.d/xxx.key]
Acls=user::rw-;group::---;other::---

[/home/xxx/.gnupg/pubring.kbx]
Acls=user::rw-;group::r--;other::r--

[/home/xxx/.gnupg/pubring.kbx~]
Acls=user::rw-;group::---;other::---

[/home/xxx/.gnupg/trustdb.gpg]
Acls=user::rw-;group::---;other::---

[/home/xxx/.ssh]
Acls=user::rwx;group::r--;other::r--
[/home/xxx/.ssh/id_rsa]
Acls=user::rw-;group::---;other::---
[/home/xxx/.ssh/id_rsa.pem]
Acls=user::rw-;group::r--;other::r--
[/home/xxx/.ssh/id_rsa.pub]
Acls=user::rw-;group::r--;other::r--
[/home/xxx/.ssh/known_hosts]
Acls=user::rw-;group::---;other::---
[/home/xxx/.ssh/known_hosts.old]
Acls=user::rw-;group::r--;other::r--
[Defaults]
Excludes=
Includes=/home/xxx/.ssh;/home/xxx/.gnupg/;
SaveAcls=true
```

Then I get a error when I rerun my programe:

erminate called after throwing an instance of 'std::logic_error'
  what():  l4: ini parsing failed, section not closed

But I can't find any error about this ini file :(

**Comment by Rookfighter** [comment]
its the `#` symbol in line 4. `#` starts a comment so everything after that `#` is interpreted as comment, so the closing bracket of the section `]` is interpreted as comment. Use `\#` to escape the hash symbol. I will verify this solution as soon as possible.

**Comment by cathaysia** [comment]
Sorry, I don't know why the answer not be uploaded last time. I edit this again.

I had try your way, it works when I write it at first, but when I write ini again, `\#` be recovered automated :(

When I first write file:

```ini
[/home/xxx/.gnupg/]
Acls=user::rwx;group::---;other::---

[/home/xxx/.gnupg/.\#lk0x00005648c0e23490.fedora.29271]
Acls=user::rw-;group::r--;other::r--

```
write this file again:
```
[/home/xxx/.gnupg/]
Acls=user::rwx;group::---;other::---
[/home/xxx/.gnupg/.#lk0x00005648c0e23490.fedora.29271]
Acls=user::rw-;group::r--;other::r--
[/home/xxx/.gnupg/openpgp-revocs.d/D7394F3CF66F676B6030C77F7EA203FF0732DAFB.rev]
Acls=user::rw-;group::---;other::---
[/home/xxx/.gnupg/private-keys-v1.d/3F2387B5A27C2F624CB7379D875F6F8758B1EA7B.key]
Acls=user::rw-;group::---;other::---

```

I promise not replace `\#`  with "#"

**Comment by Rookfighter** [comment]
Thanks, looks like a bug, where the comment character is not properly escaped, when the file is written. I will look into fixing this !

**Comment by Rookfighter** [comment]
Hi @cathaysia 

The bug should be fixed with the most recent head of master. Sorry for the delay and thanks for waiting.
The basic issue was that comment characters were not escaped correctly when writing the inifile.
inifile-cpp should now provide consistent loading and saving, meaning that it should be able to parse anything that it has written itself.
